apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mvhe

commonLabels:
  app: mvhe
  app.kubernetes.io/name: mvhe
  app.kubernetes.io/part-of: mvhe

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
