apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    access: proxy
    url: timescaledb:5432
    database: mvhe
    user: mvhe
    secureJsonData:
      password: "$POSTGRES_PASSWORD"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: clickhouse:8123
    jsonData:
      defaultDatabase: mvhe
